"""initial schema

Revision ID: c82043965a44
Revises: 
Create Date: 2026-05-09 01:57:38.596030

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c82043965a44'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feeds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('poll_interval_seconds', sa.Integer(), server_default=sa.text('3600'), nullable=False),
    sa.Column('active_xpath_extractor_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'paused', 'failed')", name=op.f('ck_feeds_status_valid')),
    sa.CheckConstraint('poll_interval_seconds > 0', name=op.f('ck_feeds_poll_interval_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feeds')),
    sa.UniqueConstraint('url', name=op.f('uq_feeds_url'))
    )
    op.create_index('ix_feeds_status_last_scraped_at', 'feeds', ['status', 'last_scraped_at'], unique=False)
    op.create_table('xpath_extractors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feed_id', sa.UUID(), nullable=False),
    sa.Column('xpath', sa.String(), nullable=False),
    sa.Column('generated_by', sa.String(), nullable=False),
    sa.Column('llm_model', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], name=op.f('fk_xpath_extractors_feed_id_feeds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_xpath_extractors'))
    )
    op.create_index('ix_xpath_extractors_feed_id_created_at', 'xpath_extractors', ['feed_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('scrape_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feed_id', sa.UUID(), nullable=False),
    sa.Column('xpath_extractor_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('raw_html', sa.String(), nullable=True),
    sa.Column('items_seen', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('items_new', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.CheckConstraint("status IN ('running', 'success', 'failed', 'xpath_regenerated')", name=op.f('ck_scrape_runs_status_valid')),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], name=op.f('fk_scrape_runs_feed_id_feeds'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['xpath_extractor_id'], ['xpath_extractors.id'], name=op.f('fk_scrape_runs_xpath_extractor_id_xpath_extractors'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scrape_runs'))
    )
    op.create_index('ix_scrape_runs_feed_id_started_at', 'scrape_runs', ['feed_id', sa.literal_column('started_at DESC')], unique=False)
    op.create_index('ix_scrape_runs_started_at', 'scrape_runs', ['started_at'], unique=False)
    op.create_table('feed_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feed_id', sa.UUID(), nullable=False),
    sa.Column('guid', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('scrape_run_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], name=op.f('fk_feed_items_feed_id_feeds'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scrape_run_id'], ['scrape_runs.id'], name=op.f('fk_feed_items_scrape_run_id_scrape_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feed_items')),
    sa.UniqueConstraint('feed_id', 'guid', name='uq_feed_items_feed_id_guid')
    )
    op.create_index('ix_feed_items_feed_id_first_seen_at', 'feed_items', ['feed_id', sa.literal_column('first_seen_at DESC')], unique=False)
    # Deferrable FK on feeds.active_xpath_extractor_id; created after both tables
    # exist so the circular relationship between feeds and xpath_extractors can
    # be inserted in a single transaction.
    op.create_foreign_key(
        'fk_feeds_active_xpath_extractor_id_xpath_extractors',
        'feeds',
        'xpath_extractors',
        ['active_xpath_extractor_id'],
        ['id'],
        ondelete='SET NULL',
        deferrable=True,
        initially='DEFERRED',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_feeds_active_xpath_extractor_id_xpath_extractors',
        'feeds',
        type_='foreignkey',
    )
    op.drop_index('ix_feed_items_feed_id_first_seen_at', table_name='feed_items')
    op.drop_table('feed_items')
    op.drop_index('ix_scrape_runs_started_at', table_name='scrape_runs')
    op.drop_index('ix_scrape_runs_feed_id_started_at', table_name='scrape_runs')
    op.drop_table('scrape_runs')
    op.drop_index('ix_xpath_extractors_feed_id_created_at', table_name='xpath_extractors')
    op.drop_table('xpath_extractors')
    op.drop_index('ix_feeds_status_last_scraped_at', table_name='feeds')
    op.drop_table('feeds')
    # ### end Alembic commands ###
