"""add last_seen_at to feed_items

Revision ID: dc8b402c1726
Revises: c82043965a44
Create Date: 2026-05-09 02:53:24.098690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc8b402c1726'
down_revision: Union[str, Sequence[str], None] = 'c82043965a44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed_items', sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feed_items', 'last_seen_at')
    # ### end Alembic commands ###
